### ISSUE TITLE
java.lang.ArithmeticException: / by zero 

### ISSUE THREAD

**Issue by hi-mamba** [kurtloong/acreath-starter-threadpool#1]
https://github.com/kurtloong/acreath-starter-threadpool/blob/ca79e104e809735903746dde279166ef7a35608c/src/main/java/com/github/kurtloong/endpoint/ThreadPoolEndpoint.java#L139

项目启动完成，直接请求接口 /actuator/threadpool/getThreadPoolListInfo  会出现这个异常，应该需要判断下 threadPool.getTaskCount() 为 0 的情况

**Comment by kurtloong** [comment]
非常感谢您，已经修复
